FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Installing git
RUN apt-get update && apt-get install -y git

# Copy requirements first to leverage Docker cache
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose Flask port
EXPOSE 5000

# Command to run the Flask development server
CMD ["python", "main.py"]